In [1]:
import pandas as pd
import numpy as np

In [5]:
# 1. Absolute Maximum Scaling

df = pd.read_csv ('housing.csv')
df = df.select_dtypes(include = np.number)
df.head()

       Price  Bedroom  Bathroom  Floors  Parking    Year
0   90000000        6         3     2.0       10  2073.0
1   80000000        5         3     2.0        9  2073.0
2   70000000        5         3     2.0       12  2071.0
3  130000000        6         4     3.0        9  2017.0
4  100000000        6         3     2.0       10  2070.0

In [6]:
max_abs = np.max(np.abs(df), axis=0)

scaled_df = df / max_abs

scaled_df.head()

          Price   Bedroom  Bathroom    Floors   Parking      Year
0  4.166667e-07  0.063158     0.075  0.153846  0.322581  0.998074
1  3.703704e-07  0.052632     0.075  0.153846  0.290323  0.998074
2  3.240741e-07  0.052632     0.075  0.153846  0.387097  0.997111
3  6.018518e-07  0.063158     0.100  0.230769  0.290323  0.971112
4  4.629630e-07  0.063158     0.075  0.153846  0.322581  0.996630

In [9]:
# 2. Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

scaled_df.head()

          Price   Bedroom  Bathroom    Floors   Parking      Year
0  4.166666e-07  0.063158     0.075  0.153846  0.322581  0.951807
1  3.703703e-07  0.052632     0.075  0.153846  0.290323  0.951807
2  3.240740e-07  0.052632     0.075  0.153846  0.387097  0.927711
3  6.018518e-07  0.063158     0.100  0.230769  0.290323  0.277108
4  4.629629e-07  0.063158     0.075  0.153846  0.322581  0.915663

In [10]:
df.head()

       Price  Bedroom  Bathroom  Floors  Parking    Year
0   90000000        6         3     2.0       10  2073.0
1   80000000        5         3     2.0        9  2073.0
2   70000000        5         3     2.0       12  2071.0
3  130000000        6         4     3.0        9  2017.0
4  100000000        6         3     2.0       10  2070.0

In [ ]:
# 3. Normalization (Vector Normalization) used in classification ans clustering

from sklearn.preprocessing import Normalizer
import pandas as pd

# Initialize the vector normalizer
scaler = Normalizer()

# Corrected the typo 'fit_transfrom' to 'fit_transform'
scaled_data = scaler.fit_transform(df)

# Convert the resulting numpy array back into a Pandas DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)
scaled_df.head()

In [15]:
# 4. Standardization

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
                         columns=df.columns)
print(scaled_df.head())

      Price   Bedroom  Bathroom    Floors   Parking      Year
0 -0.053732  0.783100  0.428386 -0.651648  4.293437  0.583673
1 -0.053734  0.543488  0.428386 -0.651648  3.815981  0.583673
2 -0.053735  0.543488  0.428386 -0.651648  5.248351  0.506974
3 -0.053727  0.783100  0.807859  0.138989  3.815981 -1.563884
4 -0.053731  0.783100  0.428386 -0.651648  4.293437  0.468625

In [16]:
# 5. Robust Scaling
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data,
                         columns=df.columns)
print(scaled_df.head())

      Price  Bedroom  Bathroom  Floors  Parking      Year
0  3.253968      1.2      0.75    -1.0     10.0 -0.017857
1  2.857143      1.0      0.75    -1.0      9.0 -0.017857
2  2.460317      1.0      0.75    -1.0     12.0 -0.053571
3  4.841270      1.2      1.00     0.0      9.0 -1.017857
4  3.650794      1.2      0.75    -1.0     10.0 -0.071429